export const diSidebar = [
    {
        text: "分布式理论",
        link: "/di/theory/",
        items: [
            { text: "CAP 定理", link: "/di/theory/cap" },
            { text: "CAP 定理证明与理解误区", link: "/di/theory/cap-misunderstanding" },
            { text: "BASE 理论", link: "/di/theory/base" },
            { text: "CAP 与 BASE 的关系", link: "/di/theory/cap-base-relation" },
            { text: "PACELC 定理", link: "/di/theory/pacelc" },
            { text: "强一致性 vs 最终一致性", link: "/di/theory/consistency-models" },
            { text: "线性一致性 vs 顺序一致性", link: "/di/theory/linearizable-sequential" },
            { text: "因果一致性", link: "/di/theory/causal-consistency" },
            { text: "Quorum 读写机制", link: "/di/theory/quorum" },
            { text: "向量时钟与版本向量", link: "/di/theory/vector-clock" },
            { text: "分布式系统故障模型", link: "/di/theory/failure-models" },
            { text: "FLP  impossibility", link: "/di/theory/flp" },
            { text: "Paxos 算法（Basic / Multi-Paxos）", link: "/di/theory/paxos" },
            { text: "Raft 算法（领导者选举/日志复制）", link: "/di/theory/raft" },
            { text: "拜占庭将军问题与 PBFT", link: "/di/theory/byzantine-pbft" },
        ],
    },
    {
        text: "分布式事务",
        link: "/di/transaction/",
        items: [
            { text: "分布式事务概述与场景", link: "/di/transaction/overview" },
            { text: "2PC（两阶段提交）", link: "/di/transaction/2pc" },
            { text: "2PC 的阻塞问题与缺陷", link: "/di/transaction/2pc-problems" },
            { text: "3PC（三阶段提交）", link: "/di/transaction/3pc" },
            { text: "2PC vs 3PC 对比", link: "/di/transaction/2pc-vs-3pc" },
            { text: "TCC（Try-Confirm-Cancel）", link: "/di/transaction/tcc" },
            { text: "TCC 空回滚与防悬挂", link: "/di/transaction/tcc-pitfalls" },
            { text: "TCC 幂等性设计", link: "/di/transaction/tcc-idempotency" },
            { text: "Saga 事务", link: "/di/transaction/saga" },
            { text: "Saga 正向恢复 vs 反向恢复", link: "/di/transaction/saga-recovery" },
            { text: "本地消息表", link: "/di/transaction/local-message-table" },
            { text: "RocketMQ 事务消息", link: "/di/transaction/rocketmq-transaction" },
            { text: "Seata AT 模式原理", link: "/di/transaction/seata-at" },
            { text: "Seata TCC 模式", link: "/di/transaction/seata-tcc" },
            { text: "分布式事务方案选型矩阵", link: "/di/transaction/selection" },
        ],
    },
    {
        text: "分布式锁",
        link: "/di/lock/",
        items: [
            { text: "分布式锁设计目标", link: "/di/lock/goals" },
            { text: "数据库乐观锁实现分布式锁", link: "/di/lock/db-optimistic" },
            { text: "数据库悲观锁实现分布式锁", link: "/di/lock/db-pessimistic" },
            { text: "Redis 分布式锁（SETNX + Lua）", link: "/di/lock/redis-lock" },
            { text: "Redis 锁过期续期问题", link: "/di/lock/redis-lease" },
            { text: "RedLock 算法", link: "/di/lock/redlock" },
            { text: "RedLock 争议与批评", link: "/di/lock/redlock-criticism" },
            { text: "ZooKeeper 分布式锁", link: "/di/lock/zookeeper-lock" },
            { text: "etcd 分布式锁", link: "/di/lock/etcd-lock" },
            { text: "三种分布式锁方案对比", link: "/di/lock/comparison" },
            { text: "分布式锁选型建议", link: "/di/lock/selection" },
        ],
    },
    {
        text: "三高架构（高性能/高并发/高可用）",
        link: "/di/high-availability/",
        items: [
            { text: "高性能设计概览", link: "/di/high-availability/performance-overview" },
            { text: "数据库高性能设计", link: "/di/high-availability/db-performance" },
            { text: "缓存高性能设计", link: "/di/high-availability/cache-performance" },
            { text: "异步化与消息队列", link: "/di/high-availability/asynchronous" },
            { text: "高并发设计概览", link: "/di/high-availability/concurrency-overview" },
            { text: "限流算法（令牌桶/漏桶/滑动窗口）", link: "/di/high-availability/rate-limiting" },
            { text: "降级与熔断", link: "/di/high-availability/degradation-circuitbreaker" },
            { text: "削峰填谷", link: "/di/high-availability/peak-cutting" },
            { text: "高可用设计概览", link: "/di/high-availability/availability-overview" },
            { text: "冗余与故障转移", link: "/di/high-availability/redundancy" },
            { text: "数据备份与恢复（RPO/RTO）", link: "/di/high-availability/backup-recovery" },
            { text: "多活架构（同城双活/两地三中心）", link: "/di/high-availability/multi-active" },
            { text: "单元化架构", link: "/di/high-availability/unit-architecture" },
            { text: "健康检查与自愈", link: "/di/high-availability/health-check" },
            { text: "全链路压测", link: "/di/high-availability/full-link-test" },
            { text: "混沌工程", link: "/di/high-availability/chaos-engineering" },
        ],
    },
];