export const dsSidebar = [
    {
        text: "设计模式",
        link: "/ds/patterns/",
        items: [
            { text: "设计模式六大原则", link: "/ds/patterns/principles" },
            { text: "单例模式（所有写法对比）", link: "/ds/patterns/singleton" },
            { text: "单例模式线程安全与序列化问题", link: "/ds/patterns/singleton-security" },
            { text: "工厂模式（简单工厂/工厂方法/抽象工厂）", link: "/ds/patterns/factory" },
            { text: "建造者模式", link: "/ds/patterns/builder" },
            { text: "原型模式", link: "/ds/patterns/prototype" },
            { text: "代理模式（静态/动态/CGLIB）", link: "/ds/patterns/proxy" },
            { text: "适配器模式", link: "/ds/patterns/adapter" },
            { text: "装饰器模式", link: "/ds/patterns/decorator" },
            { text: "外观模式", link: "/ds/patterns/facade" },
            { text: "策略模式", link: "/ds/patterns/strategy" },
            { text: "模板方法模式", link: "/ds/patterns/template" },
            { text: "观察者模式", link: "/ds/patterns/observer" },
            { text: "责任链模式", link: "/ds/patterns/chain" },
            { text: "状态模式", link: "/ds/patterns/state" },
            { text: "命令模式", link: "/ds/patterns/command" },
            { text: "迭代器模式", link: "/ds/patterns/iterator" },
            { text: "访问者模式", link: "/ds/patterns/visitor" },
            { text: "设计模式在框架源码中的应用", link: "/ds/patterns/in-frameworks" },
        ],
    },
    {
        text: "架构模式",
        link: "/ds/architectural/",
        items: [
            { text: "MVC 模式", link: "/ds/architectural/mvc" },
            { text: "MVP 与 MVVM 模式", link: "/ds/architectural/mvp-mvvm" },
            { text: "分层架构", link: "/ds/architectural/layered" },
            { text: "六边形架构（端口与适配器）", link: "/ds/architectural/hexagonal" },
            { text: "洋葱架构", link: "/ds/architectural/onion" },
            { text: "整洁架构（Clean Architecture）", link: "/ds/architectural/clean" },
            { text: "DDD 领域驱动设计", link: "/ds/architectural/ddd" },
            { text: "DDD 核心概念（实体/值对象/聚合/领域事件）", link: "/ds/architectural/ddd-concepts" },
            { text: "CQRS 命令查询职责分离", link: "/ds/architectural/cqrs" },
            { text: "CQRS 与 DDD 结合", link: "/ds/architectural/cqrs-ddd" },
            { text: "事件驱动架构（EDA）", link: "/ds/architectural/eda" },
            { text: "事件溯源（Event Sourcing）", link: "/ds/architectural/event-sourcing" },
            { text: "CQRS + Event Sourcing 实战", link: "/ds/architectural/cqrs-es" },
            { text: "微内核架构", link: "/ds/architectural/microkernel" },
            { text: "管道-过滤器架构", link: "/ds/architectural/pipe-filter" },
            { text: "架构模式选型对比", link: "/ds/architectural/comparison" },
            { text: "微服务架构（服务拆分原则）", link: "/ds/architectural/microservices" },
            { text: "服务编排 vs 服务编排（Choreography vs Orchestration）", link: "/ds/architectural/choreography-orchestration" },
            { text: "Service Mesh（Istio / Linkerd）", link: "/ds/architectural/service-mesh" },
            { text: "云原生架构（Kubernetes + 微服务）", link: "/ds/architectural/cloud-native" },
        ],
    },
    {
        text: "系统设计",
        link: "/ds/system-design/",
        items: [
            { text: "系统设计方法论", link: "/ds/system-design/methodology" },
            { text: "系统设计面试解题框架", link: "/ds/system-design/interview-framework" },
            { text: "容量估算与延迟数据", link: "/ds/system-design/capacity-planning" },
            { text: "秒杀系统设计", link: "/ds/system-design/seckill" },
            { text: "秒杀系统热点问题处理", link: "/ds/system-design/seckill-hotspot" },
            { text: "短链系统设计", link: "/ds/system-design/short-url" },
            { text: "短链系统发号器设计", link: "/ds/system-design/short-url-id" },
            { text: "IM 即时通讯系统设计", link: "/ds/system-design/im" },
            { text: "IM 消息可靠性保证", link: "/ds/system-design/im-reliability" },
            { text: "支付系统设计", link: "/ds/system-design/payment" },
            { text: "支付系统对账设计", link: "/ds/system-design/payment-reconciliation" },
            { text: "附近的人（LBS）系统设计", link: "/ds/system-design/lbs" },
            { text: "Feed 流系统设计", link: "/ds/system-design/feed" },
            { text: "Feed 流推拉模式对比", link: "/ds/system-design/feed-push-pull" },
            { text: "评论系统设计", link: "/ds/system-design/comment" },
            { text: "排行榜系统设计", link: "/ds/system-design/leaderboard" },
            { text: "分布式 ID 生成器设计", link: "/ds/system-design/distributed-id" },
            { text: "配置中心设计", link: "/ds/system-design/config-center" },
            { text: "定时任务调度系统设计", link: "/ds/system-design/scheduler" },
            { text: "系统设计核心组件选型", link: "/ds/system-design/component-selection" },
            { text: "搜索引擎系统设计（Elasticsearch）", link: "/ds/system-design/search-engine" },
            { text: "消息推送系统设计", link: "/ds/system-design/push" },
            { text: "限流系统设计（令牌桶/漏桶/滑动窗口）", link: "/ds/system-design/rate-limiter" },
            { text: "日志系统设计（ELK）", link: "/ds/system-design/logging" },
            { text: "监控告警系统设计", link: "/ds/system-design/monitoring" },
            { text: "电商订单系统设计", link: "/ds/system-design/order" },
            { text: "电商库存系统设计", link: "/ds/system-design/inventory" },
            { text: "OAuth2 / JWT 认证系统设计", link: "/ds/system-design/oauth-jwt" },
        ],
    },
];