export const fwSidebar = [
    {
        text: "Spring",
        link: "/fw/spring/",
        items: [
            { text: "Spring IoC 容器（BeanFactory vs ApplicationContext）", link: "/fw/spring/ioc-container" },
            { text: "Bean 生命周期", link: "/fw/spring/bean-lifecycle" },
            { text: "BeanPostProcessor 原理", link: "/fw/spring/bean-post-processor" },
            { text: "循环依赖三级缓存", link: "/fw/spring/circular-dependency" },
            { text: "为什么需要三级缓存", link: "/fw/spring/three-level-cache" },
            { text: "构造器注入无法解决循环依赖", link: "/fw/spring/constructor-circular" },
            { text: "Spring AOP 原理", link: "/fw/spring/aop" },
            { text: "JDK 动态代理 vs CGLIB", link: "/fw/spring/proxy-comparison" },
            { text: "通知执行顺序", link: "/fw/spring/advice-order" },
            { text: "Spring 事务管理", link: "/fw/spring/transaction" },
            { text: "事务传播行为（7种）", link: "/fw/spring/transaction-propagation" },
            { text: "@Transactional 失效场景", link: "/fw/spring/transaction-failure" },
            { text: "Spring 事件监听机制", link: "/fw/spring/event-listener" },
            { text: "FactoryBean vs BeanFactory", link: "/fw/spring/factory-bean" },
            { text: "Spring 设计模式总结", link: "/fw/spring/design-patterns" },
        ],
    },
    {
        text: "Spring Boot",
        link: "/fw/springboot/",
        items: [
            { text: "Spring Boot 自动配置原理", link: "/fw/springboot/auto-configuration" },
            { text: "@SpringBootApplication 注解解析", link: "/fw/springboot/springboot-application" },
            { text: "Spring Boot Starter 原理", link: "/fw/springboot/starter" },
            { text: "自定义 Starter 实现", link: "/fw/springboot/custom-starter" },
            { text: "Spring Boot 配置文件加载顺序", link: "/fw/springboot/config-order" },
            { text: "Spring Boot Actuator 监控端点", link: "/fw/springboot/actuator" },
            { text: "Spring Boot 启动流程", link: "/fw/springboot/startup-process" },
            { text: "嵌入式 Web 容器原理", link: "/fw/springboot/embedded-container" },
            { text: "Spring Boot 条件注解", link: "/fw/springboot/conditional-annotations" },
        ],
    },
    {
        text: "MyBatis",
        link: "/fw/mybatis/",
        items: [
            { text: "MyBatis 核心组件", link: "/fw/mybatis/components" },
            { text: "MyBatis 执行流程", link: "/fw/mybatis/execution-flow" },
            { text: "一级缓存与二级缓存", link: "/fw/mybatis/cache" },
            { text: "二级缓存问题与解决", link: "/fw/mybatis/cache-issues" },
            { text: "动态 SQL 原理", link: "/fw/mybatis/dynamic-sql" },
            { text: "Mapper 代理原理", link: "/fw/mybatis/mapper-proxy" },
            { text: "MyBatis 与 Spring 整合原理", link: "/fw/mybatis/spring-integration" },
            { text: "MyBatis 插件机制", link: "/fw/mybatis/plugin" },
            { text: "MyBatis-Plus 常用特性", link: "/fw/mybatis/mybatis-plus" },
        ],
    },
    {
        text: "Spring Cloud",
        link: "/fw/springcloud/",
        items: [
            { text: "Spring Cloud 生态组件概览", link: "/fw/springcloud/overview" },
            { text: "服务注册与发现（Eureka/Nacos）", link: "/fw/springcloud/service-discovery" },
            { text: "Eureka 自我保护机制", link: "/fw/springcloud/eureka-self-preservation" },
            { text: "配置中心（Config/Nacos）", link: "/fw/springcloud/config-center" },
            { text: "配置热刷新原理", link: "/fw/springcloud/config-refresh" },
            { text: "服务网关（Gateway vs Zuul）", link: "/fw/springcloud/gateway" },
            { text: "Gateway 路由断言与过滤器", link: "/fw/springcloud/gateway-filters" },
            { text: "服务调用（Feign）原理", link: "/fw/springcloud/feign" },
            { text: "Feign 重试与降级", link: "/fw/springcloud/feign-retry" },
            { text: "负载均衡（Ribbon/LoadBalancer）", link: "/fw/springcloud/loadbalancer" },
            { text: "服务熔断（Hystrix/Sentinel）", link: "/fw/springcloud/circuit-breaker" },
            { text: "Sentinel 限流规则", link: "/fw/springcloud/sentinel" },
            { text: "分布式链路追踪（Sleuth+Zipkin）", link: "/fw/springcloud/tracing" },
            { text: "Nacos 服务发现与配置管理", link: "/fw/springcloud/nacos" },
        ],
    },
    {
        text: "消息队列",
        link: "/fw/mq/",
        items: [
            { text: "消息队列应用场景", link: "/fw/mq/scenarios" },
            { text: "消息队列选型矩阵", link: "/fw/mq/selection" },
            { text: "消息积压处理策略", link: "/fw/mq/backlog" },
            { text: "MQ 高并发问题解决方案", link: "/fw/mq/high-concurrency" },
            {
                text: "Kafka",
                link: "/fw/mq/kafka/",
                items: [
                    { text: "Kafka 架构深度解析", link: "/fw/mq/kafka/architecture" },
                    { text: "Kafka 分区与消费者组", link: "/fw/mq/kafka/partition" },
                    { text: "Kafka 消息可靠性保证", link: "/fw/mq/kafka/reliability" },
                    { text: "Kafka 顺序消息实现", link: "/fw/mq/kafka/ordering" },
                    { text: "Kafka 消息丢失与重复消费", link: "/fw/mq/kafka/message-loss" },
                    { text: "Kafka 存储机制与日志分段", link: "/fw/mq/kafka/storage" },
                    { text: "Kafka 索引机制与零拷贝", link: "/fw/mq/kafka/kafka-index" },
                    { text: "Kafka 控制器选举", link: "/fw/mq/kafka/controller" },
                    { text: "Kafka Rebalance 机制", link: "/fw/mq/kafka/rebalance" },
                    { text: "Kafka 日志压缩与清理策略", link: "/fw/mq/kafka/cleanup" },
                    { text: "Kafka Offset 管理", link: "/fw/mq/kafka/offset" },
                ],
            },
            {
                text: "RocketMQ",
                link: "/fw/mq/rocketmq/",
                items: [
                    { text: "RocketMQ 架构深度解析", link: "/fw/mq/rocketmq/architecture" },
                    { text: "RocketMQ 事务消息", link: "/fw/mq/rocketmq/transaction" },
                    { text: "RocketMQ 顺序消息", link: "/fw/mq/rocketmq/ordering" },
                    { text: "RocketMQ 延迟消息", link: "/fw/mq/rocketmq/delay" },
                    { text: "RocketMQ 消息过滤", link: "/fw/mq/rocketmq/filter" },
                    { text: "RocketMQ 消费模式（集群/广播）", link: "/fw/mq/rocketmq/consume-mode" },
                    { text: "RocketMQ 高可用机制", link: "/fw/mq/rocketmq/ha" },
                ],
            },
            {
                text: "RabbitMQ",
                link: "/fw/mq/rabbitmq/",
                items: [
                    { text: "RabbitMQ 架构与 AMQP 协议", link: "/fw/mq/rabbitmq/architecture" },
                    { text: "交换机类型（Direct/Topic/Fanout/Headers）", link: "/fw/mq/rabbitmq/exchange-types" },
                    { text: "Queue 与消息存储机制", link: "/fw/mq/rabbitmq/queue" },
                    { text: "Binding 与 Routing Key", link: "/fw/mq/rabbitmq/binding" },
                    { text: "消息可靠性投递（Confirm/Return）", link: "/fw/mq/rabbitmq/reliability" },
                    { text: "死信队列（DLX）应用场景", link: "/fw/mq/rabbitmq/dead-letter" },
                    { text: "延迟队列与延迟插件", link: "/fw/mq/rabbitmq/delay-queue" },
                    { text: "TTL 消息与优先级队列", link: "/fw/mq/rabbitmq/ttl-priority" },
                    { text: "消息幂等性与去重", link: "/fw/mq/rabbitmq/idempotency" },
                    { text: "RabbitMQ 集群与镜像队列", link: "/fw/mq/rabbitmq/cluster" },
                    { text: "RabbitMQ 权限管理与安全", link: "/fw/mq/rabbitmq/security" },
                    { text: "RabbitMQ 常见问题与排查", link: "/fw/mq/rabbitmq/troubleshooting" },
                ],
            },
        ],
    },
    {
        text: "RPC 与注册中心",
        link: "/fw/rpc/",
        items: [
            { text: "RPC 调用原理", link: "/fw/rpc/rpc-principle" },
            { text: "Dubbo 架构深度解析", link: "/fw/rpc/dubbo-architecture" },
            { text: "Dubbo 服务暴露与引用", link: "/fw/rpc/dubbo-export" },
            { text: "Dubbo 负载均衡策略", link: "/fw/rpc/dubbo-loadbalance" },
            { text: "Dubbo 容错机制", link: "/fw/rpc/dubbo-fault-tolerance" },
            { text: "Dubbo 泛化调用", link: "/fw/rpc/dubbo-generic" },
            { text: "gRPC 与 Protocol Buffers", link: "/fw/rpc/grpc" },
            { text: "gRPC 四种通信模式", link: "/fw/rpc/grpc-modes" },
            { text: "Dubbo vs gRPC vs Feign", link: "/fw/rpc/rpc-comparison" },
            { text: "ZooKeeper 核心概念", link: "/fw/rpc/zookeeper" },
            { text: "ZooKeeper 数据模型与 ZAB 协议", link: "/fw/rpc/zookeeper-zab" },
            { text: "ZooKeeper 应用场景", link: "/fw/rpc/zookeeper-scenarios" },
            { text: "Nacos 架构解析", link: "/fw/rpc/nacos" },
            { text: "ZooKeeper vs Nacos vs Eureka", link: "/fw/rpc/registry-comparison" },
        ],
    },
    {
        text: "搜索引擎",
        link: "/fw/search/",
        items: [
            { text: "Elasticsearch 核心概念（索引/分片/副本）", link: "/fw/search/es-concepts" },
            { text: "Elasticsearch 写入流程", link: "/fw/search/es-write" },
            { text: "Elasticsearch 查询流程", link: "/fw/search/es-query" },
            { text: "Elasticsearch 倒排索引原理", link: "/fw/search/inverted-index" },
            { text: "ES 分词器与中文分词", link: "/fw/search/analyzer" },
            { text: "ES 集群与分片分配", link: "/fw/search/cluster" },
            { text: "Elasticsearch vs Solr", link: "/fw/search/es-vs-solr" },
        ],
    },
    {
        text: "其他中间件",
        link: "/fw/other/",
        items: [
            { text: "Quartz 定时任务调度", link: "/fw/other/quartz" },
            { text: "XXL-JOB 分布式调度", link: "/fw/other/xxl-job" },
            { text: "ElasticJob 原理", link: "/fw/other/elastic-job" },
            { text: "ShardingSphere 分库分表", link: "/fw/other/shardingsphere" },
            { text: "Apollo 配置中心", link: "/fw/other/apollo" },
            { text: "Nacos 配置中心", link: "/fw/other/nacos-config" },
        ],
    },
];