export const ivSidebar = [
    {
        text: "面试流程与时间线",
        link: "/iv/process/",
        items: [
            { text: "简历投递渠道对比", link: "/iv/process/channels" },
            { text: "大厂面试流程详解（阿里/腾讯/字节/美团）", link: "/iv/process/flow" },
            { text: "面试轮次与考察重点", link: "/iv/process/rounds" },
            { text: "时间线规划（1个月/3个月/6个月冲刺）", link: "/iv/process/timeline" },
            { text: "面试前中后 Checklist", link: "/iv/process/checklist" },
        ],
    },
    {
        text: "简历编写技巧（STAR法则）",
        link: "/iv/resume/",
        items: [
            { text: "STAR 法则详解", link: "/iv/resume/star" },
            { text: "技术栈关键词优化", link: "/iv/resume/keywords" },
            { text: "项目描述模板与案例", link: "/iv/resume/project-template" },
            { text: "简历常见问题与避坑", link: "/iv/resume/pitfalls" },
            { text: "不同级别简历差异（P5/P6/P7）", link: "/iv/resume/level-diff" },
            { text: "简历投递后的跟进策略", link: "/iv/resume/followup" },
        ],
    },
    {
        text: "行为面试（BQ）题库与回答模板",
        link: "/iv/behavioral/",
        items: [
            { text: "BQ 回答框架（STAR/CAR/PPP）", link: "/iv/behavioral/framework" },
            { text: "亚麻16条领导力原则与对应BQ题", link: "/iv/behavioral/amazon" },
            { text: "常见BQ题50道（分类解析）", link: "/iv/behavioral/questions" },
            { text: "失败/冲突/挑战类问题回答技巧", link: "/iv/behavioral/difficult" },
            { text: "优缺点/职业规划/为什么离职", link: "/iv/behavioral/personal" },
            { text: "如何判断面试官在挖BQ坑", link: "/iv/behavioral/traps" },
            { text: "BQ 回答评分标准（面试官视角）", link: "/iv/behavioral/scoring" },
        ],
    },
    {
        text: "智力题与逻辑题 20 道",
        link: "/iv/puzzles/",
        items: [
            { text: "概率题（生日悖论/抽球问题）", link: "/iv/puzzles/probability" },
            { text: "博弈题（海盗分金/毒药问题）", link: "/iv/puzzles/game" },
            { text: "估算题（芝加哥钢琴师/纽约加油站）", link: "/iv/puzzles/estimation" },
            { text: "逻辑推理题（真假话/天平称重）", link: "/iv/puzzles/logic" },
            { text: "数学题（时针分针重合/青蛙爬井）", link: "/iv/puzzles/math" },
            { text: "智力题解题方法论", link: "/iv/puzzles/methodology" },
        ],
    },
    {
        text: "HR面与薪资谈判技巧",
        link: "/iv/hr/",
        items: [
            { text: "HR面考察的5个维度", link: "/iv/hr/dimensions" },
            { text: "期望薪资的回答技巧", link: "/iv/hr/salary-answer" },
            { text: "薪资构成解析（base/奖金/股票/期权）", link: "/iv/hr/compensation" },
            { text: "股票/期权的计算方式", link: "/iv/hr/stock-option" },
            { text: "如何评估一个Offer的真实价值", link: "/iv/hr/offer-evaluation" },
            { text: "谈判话术：收到多个Offer怎么谈", link: "/iv/hr/negotiation" },
            { text: "背调注意事项与应对", link: "/iv/hr/background-check" },
            { text: "HR面常见的5个坑", link: "/iv/hr/pitfalls" },
        ],
    },
    {
        text: "大厂面经与岗位匹配",
        link: "/iv/experience/",
        items: [
            { text: "阿里/蚂蚁 面经汇总（P5/P6/P7）", link: "/iv/experience/alibaba" },
            { text: "腾讯 面经汇总（T2/T3/T4）", link: "/iv/experience/tencent" },
            { text: "字节跳动 面经汇总（1-1/1-2/2-1/2-2）", link: "/iv/experience/bytedance" },
            { text: "美团 面经汇总（L5/L6/L7）", link: "/iv/experience/meituan" },
            { text: "百度/京东/滴滴/拼多多 面经", link: "/iv/experience/others" },
            { text: "外企（微软/亚马逊/Google）面试特点", link: "/iv/experience/foreign" },
            { text: "岗位级别对标（P5-P8/T2-1到T4/L5-L8）", link: "/iv/experience/levels" },
            { text: "如何根据面经针对性准备", link: "/iv/experience/preparation" },
        ],
    },
    {
        text: "面试复盘与 Offer 选择",
        link: "/iv/review/",
        items: [
            { text: "面试记录与复盘模板", link: "/iv/review/template" },
            { text: "挂面原因分析", link: "/iv/review/failure-analysis" },
            { text: "Offer 综合评估维度", link: "/iv/review/offer-evaluation" },
            { text: "团队/业务/技术栈评估方法", link: "/iv/review/team-assessment" },
            { text: "入职后的 30-60-90 天计划", link: "/iv/review/onboarding" },
            { text: "如何优雅地拒绝 Offer", link: "/iv/review/reject-offer" },
        ],
    },
];