export const jaSidebar = [
    {
        text: "Java 基础",
        link: "/ja/basic/",
        items: [
            { text: "面向对象三大特性（封装/继承/多态）", link: "/ja/basic/oop" },
            { text: "重载 vs 重写", link: "/ja/basic/overload-override" },
            { text: "值传递 vs 引用传递", link: "/ja/basic/pass-by-value" },
            { text: "== 与 equals 区别", link: "/ja/basic/equals" },
            { text: "String/StringBuilder/StringBuffer 对比", link: "/ja/basic/string" },
            { text: "异常体系（Error/Exception/RuntimeException）", link: "/ja/basic/exception" },
            { text: "checked vs unchecked 异常", link: "/ja/basic/checked-unchecked" },
            { text: "try-catch-finally 执行顺序", link: "/ja/basic/try-catch" },
            { text: "反射原理与应用场景", link: "/ja/basic/reflection" },
            { text: "泛型（类型擦除/通配符/上下界）", link: "/ja/basic/generic" },
            { text: "注解（元注解/运行时注解）", link: "/ja/basic/annotation" },
            { text: "内部类（成员/静态/局部/匿名）", link: "/ja/basic/inner-class" },
        ],
    },
    {
        text: "集合框架",
        link: "/ja/collection/",
        items: [
            { text: "ArrayList 源码与扩容机制", link: "/ja/collection/arraylist" },
            { text: "LinkedList 源码与双端队列", link: "/ja/collection/linkedlist" },
            { text: "ArrayList vs LinkedList 对比", link: "/ja/collection/list-comparison" },
            { text: "HashMap 源码深度解析", link: "/ja/collection/hashmap" },
            { text: "HashMap 扩容机制（resize）", link: "/ja/collection/hashmap-resize" },
            { text: "HashMap 红黑树化阈值设计", link: "/ja/collection/hashmap-treeify" },
            { text: "LinkedHashMap 实现 LRU 缓存", link: "/ja/collection/linkedhashmap" },
            { text: "TreeMap 与红黑树", link: "/ja/collection/treemap" },
            { text: "HashSet 与 HashMap 关系", link: "/ja/collection/hashset" },
            { text: "ConcurrentHashMap JDK7 vs JDK8", link: "/ja/collection/concurrent-hashmap" },
            { text: "ConcurrentHashMap put 流程", link: "/ja/collection/concurrent-hashmap-put" },
            { text: "ConcurrentHashMap 扩容机制", link: "/ja/collection/concurrent-hashmap-resize" },
            { text: "HashMap vs Hashtable vs ConcurrentHashMap", link: "/ja/collection/map-comparison" },
        ],
    },
    {
        text: "并发编程",
        link: "/ja/concurrent/",
        items: [
            { text: "进程 vs 线程 vs 协程", link: "/ja/concurrent/process-thread-coroutine" },
            { text: "Java内存模型（JMM）", link: "/ja/concurrent/jmm" },
            { text: "happens-before 原则", link: "/ja/concurrent/happens-before" },
            { text: "volatile 可见性与禁止重排序", link: "/ja/concurrent/volatile" },
            { text: "synchronized 原理与锁升级", link: "/ja/concurrent/synchronized" },
            { text: "synchronized 对象头（Mark Word）", link: "/ja/concurrent/mark-word" },
            { text: "synchronized vs ReentrantLock", link: "/ja/concurrent/sync-vs-reentrantlock" },
            { text: "CAS 原理与 ABA 问题", link: "/ja/concurrent/cas" },
            { text: "AQS 抽象队列同步器原理", link: "/ja/concurrent/aqs" },
            { text: "ReentrantLock 公平锁 vs 非公平锁", link: "/ja/concurrent/reentrantlock" },
            { text: "ReentrantReadWriteLock 读写锁", link: "/ja/concurrent/readwritelock" },
            { text: "Condition 条件队列", link: "/ja/concurrent/condition" },
            { text: "CountDownLatch 原理与使用", link: "/ja/concurrent/countdownlatch" },
            { text: "CyclicBarrier 原理与使用", link: "/ja/concurrent/cyclicbarrier" },
            { text: "Semaphore 信号量", link: "/ja/concurrent/semaphore" },
            { text: "ThreadLocal 原理与内存泄漏", link: "/ja/concurrent/threadlocal" },
            { text: "线程池 7 个核心参数", link: "/ja/concurrent/threadpool-params" },
            { text: "线程池 execute 流程", link: "/ja/concurrent/threadpool-execute" },
            { text: "线程池拒绝策略对比", link: "/ja/concurrent/reject-policy" },
            { text: "线程池大小如何设置", link: "/ja/concurrent/threadpool-size" },
            { text: "阻塞队列（Array/Linked/Synchronous/Delay）", link: "/ja/concurrent/blocking-queue" },
            { text: "CompletableFuture 异步编程", link: "/ja/concurrent/completable-future" },
            { text: "Fork/Join 框架", link: "/ja/concurrent/fork-join" },
        ],
    },
    {
        text: "JVM",
        link: "/ja/jvm/",
        items: [
            { text: "JVM 运行时数据区", link: "/ja/jvm/runtime-data-area" },
            { text: "堆内存分代（新生代/老年代/元空间）", link: "/ja/jvm/heap" },
            { text: "栈帧结构（局部变量表/操作数栈）", link: "/ja/jvm/stack-frame" },
            { text: "对象内存布局（对象头/实例数据/对齐填充）", link: "/ja/jvm/object-layout" },
            { text: "对象创建流程", link: "/ja/jvm/object-creation" },
            { text: "逃逸分析与栈上分配", link: "/ja/jvm/escape-analysis" },
            { text: "垃圾回收判定（引用计数/可达性分析）", link: "/ja/jvm/gc-judgment" },
            { text: "GC Roots 有哪些", link: "/ja/jvm/gc-roots" },
            { text: "四种引用类型（强/软/弱/虚）", link: "/ja/jvm/reference-types" },
            { text: "垃圾回收算法（标记清除/复制/标记整理）", link: "/ja/jvm/gc-algorithms" },
            { text: "分代收集理论", link: "/ja/jvm/generational" },
            { text: "Serial/Parallel/CMS 收集器", link: "/ja/jvm/collectors" },
            { text: "G1 收集器原理（Region/RSet）", link: "/ja/jvm/g1" },
            { text: "ZGC 收集器原理（染色指针/读屏障）", link: "/ja/jvm/zgc" },
            { text: "GC 日志解读与分析", link: "/ja/jvm/gc-log" },
            { text: "GC 调优方法论与案例", link: "/ja/jvm/gc-tuning" },
            { text: "类加载机制（加载/验证/准备/解析/初始化）", link: "/ja/jvm/class-loading" },
            { text: "双亲委派模型", link: "/ja/jvm/parent-delegation" },
            { text: "打破双亲委派的场景（Tomcat/SPI）", link: "/ja/jvm/break-delegation" },
            { text: "自定义类加载器实现", link: "/ja/jvm/custom-classloader" },
            { text: "内存溢出排查（OOM）", link: "/ja/jvm/oom" },
            { text: "堆转储（Heap Dump）分析", link: "/ja/jvm/heap-dump" },
        ],
    },
    {
        text: "I/O 与网络",
        link: "/ja/io/",
        items: [
            { text: "BIO（阻塞IO）原理", link: "/ja/io/bio" },
            { text: "NIO 核心组件（Channel/Buffer/Selector）", link: "/ja/io/nio" },
            { text: "AIO（异步IO）原理", link: "/ja/io/aio" },
            { text: "BIO/NIO/AIO 对比", link: "/ja/io/io-comparison" },
            { text: "零拷贝原理（mmap/sendfile）", link: "/ja/io/zero-copy" },
            { text: "Netty 线程模型（Reactor）", link: "/ja/io/netty-reactor" },
            { text: "Netty 核心组件（Channel/EventLoop/Pipeline）", link: "/ja/io/netty-components" },
            { text: "Netty 零拷贝实现", link: "/ja/io/netty-zero-copy" },
            { text: "Netty 粘包/拆包解决方案", link: "/ja/io/netty-packet" },
            { text: "序列化协议对比（Java/JSON/ProtoBuf/Hessian）", link: "/ja/io/serialization" },
        ],
    },
    {
        text: "Java 新特性",
        link: "/ja/new-features/",
        items: [
            { text: "Lambda 表达式原理", link: "/ja/new-features/lambda" },
            { text: "Stream 流操作（中间操作/终端操作）", link: "/ja/new-features/stream" },
            { text: "Optional 使用最佳实践", link: "/ja/new-features/optional" },
            { text: "新日期时间API（LocalDate/DateTimeFormatter）", link: "/ja/new-features/date-time" },
            { text: "接口默认方法与静态方法", link: "/ja/new-features/default-method" },
            { text: "模块化（JPMS）", link: "/ja/new-features/module" },
            { text: "文本块（Text Block）", link: "/ja/new-features/text-block" },
            { text: "Record 记录类", link: "/ja/new-features/record" },
            { text: "密封类（Sealed Class）", link: "/ja/new-features/sealed-class" },
            { text: "模式匹配（Pattern Matching）", link: "/ja/new-features/pattern-matching" },
            { text: "虚拟线程（Virtual Thread）原理", link: "/ja/new-features/virtual-thread" },
            { text: "结构化并发（Structured Concurrency）", link: "/ja/new-features/structured-concurrency" },
            { text: "JDK 版本特性演进总结", link: "/ja/new-features/version-evolution" },
        ],
    },
];