export const qaSidebar = [
    {
        text: "Java 基础 40 题",
        link: "/qa/java-basic/",
        items: [
            { text: "面向对象三大特性是什么", link: "/qa/java-basic/oop" },
            { text: "重载与重写有什么区别", link: "/qa/java-basic/overload-override" },
            { text: "== 与 equals 有什么区别", link: "/qa/java-basic/equals" },
            { text: "hashCode 与 equals 的关系", link: "/qa/java-basic/hashcode-equals" },
            { text: "String/StringBuilder/StringBuffer 区别", link: "/qa/java-basic/string" },
            { text: "String 为什么是不可变的", link: "/qa/java-basic/string-immutable" },
            { text: "异常体系与分类", link: "/qa/java-basic/exception" },
            { text: "checked 与 unchecked 异常区别", link: "/qa/java-basic/checked-unchecked" },
            { text: "finally 与 return 执行顺序", link: "/qa/java-basic/finally-return" },
            { text: "try-with-resources 原理", link: "/qa/java-basic/try-with-resources" },
            { text: "反射原理与应用场景", link: "/qa/java-basic/reflection" },
            { text: "反射的性能问题与优化", link: "/qa/java-basic/reflection-performance" },
            { text: "泛型与类型擦除", link: "/qa/java-basic/generic" },
            { text: "泛型通配符与上下界", link: "/qa/java-basic/generic-wildcard" },
            { text: "注解与元注解", link: "/qa/java-basic/annotation" },
            { text: "运行时注解与编译时注解", link: "/qa/java-basic/annotation-type" },
            { text: "内部类分类与区别", link: "/qa/java-basic/inner-class" },
            { text: "静态内部类与非静态内部类", link: "/qa/java-basic/static-inner" },
            { text: "值传递与引用传递", link: "/qa/java-basic/pass-by-value" },
            { text: "static 关键字作用", link: "/qa/java-basic/static" },
            { text: "final 关键字作用", link: "/qa/java-basic/final" },
            { text: "抽象类与接口区别", link: "/qa/java-basic/abstract-interface" },
            { text: "Java 8 接口默认方法", link: "/qa/java-basic/default-method" },
            { text: "浅拷贝与深拷贝", link: "/qa/java-basic/shallow-deep-copy" },
            { text: "Java 对象创建方式", link: "/qa/java-basic/object-creation" },
            { text: "BigDecimal 精度问题", link: "/qa/java-basic/bigdecimal" },
            { text: "包装类与缓存池", link: "/qa/java-basic/wrapper-cache" },
            { text: "自动装箱与拆箱", link: "/qa/java-basic/autoboxing" },
            { text: "枚举原理与应用", link: "/qa/java-basic/enum" },
            { text: "SPI 机制原理", link: "/qa/java-basic/spi" },
            { text: "Java 9 模块化", link: "/qa/java-basic/module" },
            { text: "Optional 使用最佳实践", link: "/qa/java-basic/optional" },
            { text: "Stream 流操作", link: "/qa/java-basic/stream" },
            { text: "Lambda 表达式原理", link: "/qa/java-basic/lambda" },
            { text: "方法引用类型", link: "/qa/java-basic/method-reference" },
            { text: "新日期时间 API", link: "/qa/java-basic/date-time" },
            { text: "正则表达式基础", link: "/qa/java-basic/regex" },
            { text: "国际化与本地化", link: "/qa/java-basic/i18n" },
            { text: "Java 日志框架（JUL/Log4j/Logback/SLF4J）", link: "/qa/java-basic/logging" },
            { text: "Java 调试技巧与 JDB", link: "/qa/java-basic/debug" },
        ],
    },
    {
        text: "集合框架 30 题",
        link: "/qa/collection/",
        items: [
            { text: "ArrayList 扩容机制", link: "/qa/collection/arraylist-resize" },
            { text: "ArrayList 与 LinkedList 对比", link: "/qa/collection/list-comparison" },
            { text: "LinkedList 双端队列实现", link: "/qa/collection/linkedlist-deque" },
            { text: "Vector 与 ArrayList 区别", link: "/qa/collection/vector" },
            { text: "HashMap 底层数据结构", link: "/qa/collection/hashmap-structure" },
            { text: "HashMap put 流程", link: "/qa/collection/hashmap-put" },
            { text: "HashMap 哈希算法", link: "/qa/collection/hashmap-hash" },
            { text: "HashMap 扩容机制", link: "/qa/collection/hashmap-resize" },
            { text: "HashMap 红黑树化阈值", link: "/qa/collection/hashmap-treeify" },
            { text: "HashMap 线程不安全表现", link: "/qa/collection/hashmap-thread-safety" },
            { text: "HashMap 与 Hashtable 区别", link: "/qa/collection/hashmap-hashtable" },
            { text: "LinkedHashMap 实现 LRU", link: "/qa/collection/linkedhashmap-lru" },
            { text: "TreeMap 与红黑树", link: "/qa/collection/treemap" },
            { text: "HashSet 与 HashMap 关系", link: "/qa/collection/hashset" },
            { text: "ConcurrentHashMap JDK7 分段锁", link: "/qa/collection/concurrent-hashmap-jdk7" },
            { text: "ConcurrentHashMap JDK8 CAS+synchronized", link: "/qa/collection/concurrent-hashmap-jdk8" },
            { text: "ConcurrentHashMap put 流程", link: "/qa/collection/concurrent-put" },
            { text: "ConcurrentHashMap 扩容机制", link: "/qa/collection/concurrent-resize" },
            { text: "ConcurrentHashMap size 方法", link: "/qa/collection/concurrent-size" },
            { text: "CopyOnWriteArrayList 原理", link: "/qa/collection/copyonwrite" },
            { text: "ConcurrentLinkedQueue 原理", link: "/qa/collection/concurrent-queue" },
            { text: "BlockingQueue 实现类对比", link: "/qa/collection/blocking-queue" },
            { text: "PriorityQueue 原理", link: "/qa/collection/priority-queue" },
            { text: "ArrayDeque 与 LinkedList 对比", link: "/qa/collection/array-deque" },
            { text: "集合遍历时删除元素", link: "/qa/collection/remove-during-iteration" },
            { text: "fail-fast 与 fail-safe 机制", link: "/qa/collection/fail-fast" },
            { text: "Collections 工具类常用方法", link: "/qa/collection/collections" },
            { text: "Arrays 工具类常用方法", link: "/qa/collection/arrays" },
            { text: "Comparable 与 Comparator", link: "/qa/collection/comparable-comparator" },
            { text: "集合框架整体架构图", link: "/qa/collection/architecture" },
        ],
    },
    {
        text: "并发编程 35 题",
        link: "/qa/concurrent/",
        items: [
            { text: "进程与线程区别", link: "/qa/concurrent/process-thread" },
            { text: "线程生命周期与状态转换", link: "/qa/concurrent/thread-state" },
            { text: "创建线程的几种方式", link: "/qa/concurrent/thread-create" },
            { text: "Java 内存模型（JMM）", link: "/qa/concurrent/jmm" },
            { text: "happens-before 原则", link: "/qa/concurrent/happens-before" },
            { text: "volatile 可见性原理", link: "/qa/concurrent/volatile" },
            { text: "volatile 禁止重排序", link: "/qa/concurrent/volatile-order" },
            { text: "synchronized 原理", link: "/qa/concurrent/synchronized" },
            { text: "synchronized 锁升级过程", link: "/qa/concurrent/lock-upgrade" },
            { text: "对象头与 Mark Word", link: "/qa/concurrent/mark-word" },
            { text: "synchronized vs ReentrantLock", link: "/qa/concurrent/sync-vs-lock" },
            { text: "CAS 原理与 ABA 问题", link: "/qa/concurrent/cas" },
            { text: "Atomic 原子类原理", link: "/qa/concurrent/atomic" },
            { text: "LongAdder 与 AtomicLong 对比", link: "/qa/concurrent/longadder" },
            { text: "AQS 原理", link: "/qa/concurrent/aqs" },
            { text: "ReentrantLock 公平锁与非公平锁", link: "/qa/concurrent/reentrantlock" },
            { text: "ReentrantReadWriteLock 读写锁", link: "/qa/concurrent/readwritelock" },
            { text: "Condition 条件队列", link: "/qa/concurrent/condition" },
            { text: "CountDownLatch 原理", link: "/qa/concurrent/countdownlatch" },
            { text: "CyclicBarrier 原理", link: "/qa/concurrent/cyclicbarrier" },
            { text: "Semaphore 原理", link: "/qa/concurrent/semaphore" },
            { text: "Exchanger 原理", link: "/qa/concurrent/exchanger" },
            { text: "Phaser 原理", link: "/qa/concurrent/phaser" },
            { text: "ThreadLocal 原理", link: "/qa/concurrent/threadlocal" },
            { text: "ThreadLocal 内存泄漏", link: "/qa/concurrent/threadlocal-leak" },
            { text: "InheritableThreadLocal 原理", link: "/qa/concurrent/inheritable-threadlocal" },
            { text: "线程池核心参数", link: "/qa/concurrent/threadpool-params" },
            { text: "线程池执行流程", link: "/qa/concurrent/threadpool-execute" },
            { text: "线程池拒绝策略", link: "/qa/concurrent/reject-policy" },
            { text: "线程池大小设置", link: "/qa/concurrent/threadpool-size" },
            { text: "阻塞队列对比", link: "/qa/concurrent/blocking-queue" },
            { text: "Future 与 Callable", link: "/qa/concurrent/future-callable" },
            { text: "CompletableFuture 异步编程", link: "/qa/concurrent/completable-future" },
            { text: "Fork/Join 框架", link: "/qa/concurrent/fork-join" },
            { text: "死锁条件与排查", link: "/qa/concurrent/deadlock" },
        ],
    },
    {
        text: "JVM 30 题",
        link: "/qa/jvm/",
        items: [
            { text: "JVM 运行时数据区", link: "/qa/jvm/runtime-data-area" },
            { text: "堆内存分代结构", link: "/qa/jvm/heap" },
            { text: "栈帧结构", link: "/qa/jvm/stack-frame" },
            { text: "程序计数器作用", link: "/qa/jvm/pc-register" },
            { text: "方法区与元空间区别", link: "/qa/jvm/metaspace" },
            { text: "对象内存布局", link: "/qa/jvm/object-layout" },
            { text: "对象创建流程", link: "/qa/jvm/object-creation" },
            { text: "逃逸分析与栈上分配", link: "/qa/jvm/escape-analysis" },
            { text: "GC 判定算法", link: "/qa/jvm/gc-judgment" },
            { text: "GC Roots 有哪些", link: "/qa/jvm/gc-roots" },
            { text: "四种引用类型", link: "/qa/jvm/reference-types" },
            { text: "垃圾回收算法", link: "/qa/jvm/gc-algorithms" },
            { text: "分代收集理论", link: "/qa/jvm/generational" },
            { text: "Serial 与 Parallel 收集器", link: "/qa/jvm/serial-parallel" },
            { text: "CMS 收集器原理", link: "/qa/jvm/cms" },
            { text: "CMS 并发标记与三色标记", link: "/qa/jvm/cms-mark" },
            { text: "CMS 优缺点与碎片问题", link: "/qa/jvm/cms-problems" },
            { text: "G1 收集器原理", link: "/qa/jvm/g1" },
            { text: "G1 Region 与 Remembered Set", link: "/qa/jvm/g1-region" },
            { text: "ZGC 收集器原理", link: "/qa/jvm/zgc" },
            { text: "ZGC 染色指针与读屏障", link: "/qa/jvm/zgc-pointer" },
            { text: "Shenandoah GC", link: "/qa/jvm/shenandoah" },
            { text: "GC 日志解读", link: "/qa/jvm/gc-log" },
            { text: "GC 调优案例", link: "/qa/jvm/gc-tuning" },
            { text: "类加载机制", link: "/qa/jvm/class-loading" },
            { text: "双亲委派模型", link: "/qa/jvm/parent-delegation" },
            { text: "打破双亲委派场景", link: "/qa/jvm/break-delegation" },
            { text: "自定义类加载器", link: "/qa/jvm/custom-classloader" },
            { text: "内存溢出排查", link: "/qa/jvm/oom" },
            { text: "堆转储分析（MAT/JProfiler）", link: "/qa/jvm/heap-dump" },
        ],
    },
    {
        text: "MySQL 30 题",
        link: "/qa/mysql/",
        items: [
            { text: "MySQL 架构（Server层与存储引擎层）", link: "/qa/mysql/architecture" },
            { text: "InnoDB vs MyISAM 对比", link: "/qa/mysql/innodb-myisam" },
            { text: "B+Tree 索引原理", link: "/qa/mysql/btree-index" },
            { text: "聚簇索引与二级索引", link: "/qa/mysql/clustered-secondary" },
            { text: "联合索引最左前缀原则", link: "/qa/mysql/leftmost-prefix" },
            { text: "索引失效场景", link: "/qa/mysql/index-invalidation" },
            { text: "覆盖索引与回表", link: "/qa/mysql/covering-index" },
            { text: "索引下推（ICP）", link: "/qa/mysql/icp" },
            { text: "Explain 执行计划解读", link: "/qa/mysql/explain" },
            { text: "慢查询日志与优化", link: "/qa/mysql/slow-query" },
            { text: "事务四大特性", link: "/qa/mysql/acid" },
            { text: "事务隔离级别", link: "/qa/mysql/isolation-levels" },
            { text: "脏读/不可重复读/幻读", link: "/qa/mysql/phantom-read" },
            { text: "MVCC 原理", link: "/qa/mysql/mvcc" },
            { text: "ReadView 可见性判断", link: "/qa/mysql/readview" },
            { text: "当前读与快照读", link: "/qa/mysql/current-snapshot-read" },
            { text: "锁分类（行锁/表锁/间隙锁/临键锁）", link: "/qa/mysql/locks" },
            { text: "间隙锁解决幻读", link: "/qa/mysql/gap-lock" },
            { text: "死锁排查与解决", link: "/qa/mysql/deadlock" },
            { text: "主从复制原理", link: "/qa/mysql/master-slave" },
            { text: "binlog 三种格式对比", link: "/qa/mysql/binlog" },
            { text: "读写分离架构", link: "/qa/mysql/read-write-split" },
            { text: "分库分表策略", link: "/qa/mysql/sharding" },
            { text: "分页查询优化", link: "/qa/mysql/pagination" },
            { text: "count 查询优化", link: "/qa/mysql/count-optimization" },
            { text: "JOIN 查询优化", link: "/qa/mysql/join-optimization" },
            { text: "SQL 执行顺序", link: "/qa/mysql/sql-order" },
            { text: "数据库连接池配置", link: "/qa/mysql/connection-pool" },
            { text: "MySQL 8.0 新特性", link: "/qa/mysql/mysql8-features" },
            { text: "MySQL 高可用方案（MHA/MGR）", link: "/qa/mysql/ha" },
        ],
    },
    {
        text: "Redis 25 题",
        link: "/qa/redis/",
        items: [
            { text: "Redis 数据结构及场景", link: "/qa/redis/data-structures" },
            { text: "String 底层 SDS 结构", link: "/qa/redis/sds" },
            { text: "ZSet 底层跳表原理", link: "/qa/redis/skiplist" },
            { text: "Redis 线程模型", link: "/qa/redis/thread-model" },
            { text: "Redis 单线程为什么快", link: "/qa/redis/single-thread" },
            { text: "Redis 6.0 多线程设计", link: "/qa/redis/multi-thread" },
            { text: "RDB 持久化原理", link: "/qa/redis/rdb" },
            { text: "AOF 持久化原理", link: "/qa/redis/aof" },
            { text: "RDB vs AOF 对比与选型", link: "/qa/redis/persistence" },
            { text: "缓存穿透与布隆过滤器", link: "/qa/redis/cache-penetration" },
            { text: "缓存击穿与互斥锁", link: "/qa/redis/cache-breakdown" },
            { text: "缓存雪崩与解决方案", link: "/qa/redis/cache-avalanche" },
            { text: "缓存一致性（延迟双删）", link: "/qa/redis/cache-consistency" },
            { text: "缓存淘汰策略（LRU/LFU/TTL）", link: "/qa/redis/eviction" },
            { text: "Redis 分布式锁（SETNX+Lua）", link: "/qa/redis/distributed-lock" },
            { text: "RedLock 算法与争议", link: "/qa/redis/redlock" },
            { text: "Redis 主从复制", link: "/qa/redis/master-slave" },
            { text: "Redis 哨兵机制", link: "/qa/redis/sentinel" },
            { text: "Redis Cluster 集群", link: "/qa/redis/cluster" },
            { text: "Redis 集群数据分片（Hash Slot）", link: "/qa/redis/hash-slot" },
            { text: "Redis 事务（MULTI/EXEC/WATCH）", link: "/qa/redis/transaction" },
            { text: "Redis 发布订阅", link: "/qa/redis/pub-sub" },
            { text: "Redis 与 Memcached 对比", link: "/qa/redis/redis-vs-memcached" },
            { text: "Redis 内存优化", link: "/qa/redis/memory-optimization" },
            { text: "Redis 性能调优", link: "/qa/redis/performance-tuning" },
        ],
    },
    {
        text: "Spring 25 题",
        link: "/qa/spring/",
        items: [
            { text: "IoC 与 DI 原理", link: "/qa/spring/ioc-di" },
            { text: "BeanFactory vs ApplicationContext", link: "/qa/spring/beanfactory-context" },
            { text: "Bean 生命周期", link: "/qa/spring/bean-lifecycle" },
            { text: "BeanPostProcessor 原理", link: "/qa/spring/bean-post-processor" },
            { text: "循环依赖与三级缓存", link: "/qa/spring/circular-dependency" },
            { text: "为什么需要三级缓存", link: "/qa/spring/three-level-cache" },
            { text: "构造器注入无法解决循环依赖", link: "/qa/spring/constructor-circular" },
            { text: "AOP 原理与代理模式", link: "/qa/spring/aop" },
            { text: "JDK 动态代理 vs CGLIB", link: "/qa/spring/proxy-comparison" },
            { text: "通知执行顺序", link: "/qa/spring/advice-order" },
            { text: "Spring 事务管理", link: "/qa/spring/transaction" },
            { text: "事务传播行为（7种）", link: "/qa/spring/transaction-propagation" },
            { text: "@Transactional 失效场景", link: "/qa/spring/transaction-failure" },
            { text: "声明式事务与编程式事务", link: "/qa/spring/tx-declarative-programmatic" },
            { text: "Spring 事件监听机制", link: "/qa/spring/event-listener" },
            { text: "FactoryBean vs BeanFactory", link: "/qa/spring/factory-bean" },
            { text: "Spring 设计模式总结", link: "/qa/spring/design-patterns" },
            { text: "Spring Boot 自动配置原理", link: "/qa/spring/auto-configuration" },
            { text: "@SpringBootApplication 注解", link: "/qa/spring/springboot-application" },
            { text: "Spring Boot Starter 原理", link: "/qa/spring/starter" },
            { text: "自定义 Starter 实现", link: "/qa/spring/custom-starter" },
            { text: "Spring Boot 启动流程", link: "/qa/spring/startup-process" },
            { text: "Spring Boot Actuator 监控", link: "/qa/spring/actuator" },
            { text: "MyBatis 执行流程", link: "/qa/spring/mybatis-execution-flow" },
            { text: "MyBatis 一级缓存与二级缓存", link: "/qa/spring/mybatis-cache" },
        ],
    },
    {
        text: "分布式 30 题",
        link: "/qa/distributed/",
        items: [
            { text: "CAP 定理", link: "/qa/distributed/cap" },
            { text: "BASE 理论", link: "/qa/distributed/base" },
            { text: "CAP 与 BASE 的关系", link: "/qa/distributed/cap-base" },
            { text: "一致性模型对比", link: "/qa/distributed/consistency" },
            { text: "PACELC 定理", link: "/qa/distributed/pacelc" },
            { text: "2PC 两阶段提交", link: "/qa/distributed/2pc" },
            { text: "2PC 的阻塞问题与缺陷", link: "/qa/distributed/2pc-problems" },
            { text: "3PC 三阶段提交", link: "/qa/distributed/3pc" },
            { text: "TCC 事务原理", link: "/qa/distributed/tcc" },
            { text: "TCC 空回滚与防悬挂", link: "/qa/distributed/tcc-pitfalls" },
            { text: "Saga 事务", link: "/qa/distributed/saga" },
            { text: "本地消息表", link: "/qa/distributed/local-message-table" },
            { text: "RocketMQ 事务消息", link: "/qa/distributed/rocketmq-transaction" },
            { text: "Seata AT 模式", link: "/qa/distributed/seata" },
            { text: "分布式事务方案选型", link: "/qa/distributed/transaction-selection" },
            { text: "Redis 分布式锁", link: "/qa/distributed/redis-lock" },
            { text: "ZooKeeper 分布式锁", link: "/qa/distributed/zk-lock" },
            { text: "分布式锁方案对比", link: "/qa/distributed/lock-comparison" },
            { text: "Dubbo 架构与原理", link: "/qa/distributed/dubbo" },
            { text: "Dubbo 负载均衡策略", link: "/qa/distributed/dubbo-loadbalance" },
            { text: "Dubbo 容错机制", link: "/qa/distributed/dubbo-fault" },
            { text: "ZooKeeper 数据模型", link: "/qa/distributed/zk-model" },
            { text: "ZAB 协议", link: "/qa/distributed/zab" },
            { text: "ZooKeeper 应用场景", link: "/qa/distributed/zk-scenarios" },
            { text: "Nacos 服务发现与配置", link: "/qa/distributed/nacos" },
            { text: "Nacos 与 Eureka/Consul 对比", link: "/qa/distributed/registry-comparison" },
            { text: "Kafka 架构与分区", link: "/qa/distributed/kafka" },
            { text: "Kafka 消息可靠性", link: "/qa/distributed/kafka-reliability" },
            { text: "Kafka 顺序消息", link: "/qa/distributed/kafka-order" },
            { text: "消息队列选型对比", link: "/qa/distributed/mq-selection" },
        ],
    },
    {
        text: "系统设计 20 题",
        link: "/qa/system-design/",
        items: [
            { text: "系统设计面试框架", link: "/qa/system-design/framework" },
            { text: "容量估算方法", link: "/qa/system-design/capacity-planning" },
            { text: "延迟数据速算表", link: "/qa/system-design/latency-numbers" },
            { text: "秒杀系统设计", link: "/qa/system-design/seckill" },
            { text: "秒杀系统热点处理", link: "/qa/system-design/seckill-hotspot" },
            { text: "短链系统设计", link: "/qa/system-design/short-url" },
            { text: "短链系统发号器设计", link: "/qa/system-design/short-url-id" },
            { text: "IM 即时通讯系统设计", link: "/qa/system-design/im" },
            { text: "IM 消息可靠性保证", link: "/qa/system-design/im-reliability" },
            { text: "支付系统设计", link: "/qa/system-design/payment" },
            { text: "支付系统对账设计", link: "/qa/system-design/payment-reconciliation" },
            { text: "附近的人（LBS）系统", link: "/qa/system-design/lbs" },
            { text: "Feed 流系统设计", link: "/qa/system-design/feed" },
            { text: "Feed 流推拉模式对比", link: "/qa/system-design/feed-push-pull" },
            { text: "排行榜系统设计", link: "/qa/system-design/leaderboard" },
            { text: "分布式 ID 生成器", link: "/qa/system-design/distributed-id" },
            { text: "雪花算法原理", link: "/qa/system-design/snowflake" },
            { text: "配置中心设计", link: "/qa/system-design/config-center" },
            { text: "定时任务调度系统", link: "/qa/system-design/scheduler" },
            { text: "系统设计组件选型", link: "/qa/system-design/component-selection" },
        ],
    },
    {
        text: "综合与场景题 30 题",
        link: "/qa/scenario/",
        items: [
            { text: "线上 CPU 飙升排查", link: "/qa/scenario/cpu-high" },
            { text: "线上内存泄漏排查", link: "/qa/scenario/memory-leak" },
            { text: "GC 频繁排查", link: "/qa/scenario/gc-frequent" },
            { text: "死锁排查与解决", link: "/qa/scenario/deadlock" },
            { text: "接口响应慢排查", link: "/qa/scenario/slow-response" },
            { text: "数据库连接池满排查", link: "/qa/scenario/connection-pool" },
            { text: "消息积压处理", link: "/qa/scenario/message-backlog" },
            { text: "缓存一致性场景", link: "/qa/scenario/cache-consistency" },
            { text: "分布式事务场景", link: "/qa/scenario/distributed-transaction" },
            { text: "接口幂等性设计", link: "/qa/scenario/idempotency" },
            { text: "限流降级熔断场景", link: "/qa/scenario/rate-limiting" },
            { text: "跨库分页查询", link: "/qa/scenario/cross-db-pagination" },
            { text: "数据迁移方案", link: "/qa/scenario/data-migration" },
            { text: "系统兼容性设计", link: "/qa/scenario/compatibility" },
            { text: "灰度发布方案", link: "/qa/scenario/gray-release" },
            { text: "全链路压测设计", link: "/qa/scenario/full-link-test" },
            { text: "敏感数据脱敏", link: "/qa/scenario/data-masking" },
            { text: "接口安全设计", link: "/qa/scenario/api-security" },
            { text: "OOM 排查案例", link: "/qa/scenario/oom-case" },
            { text: "StackOverflow 排查", link: "/qa/scenario/stackoverflow" },
            { text: "线程池参数设置案例", link: "/qa/scenario/threadpool-case" },
            { text: "数据库死锁案例", link: "/qa/scenario/deadlock-case" },
            { text: "Redis 大 key 排查", link: "/qa/scenario/redis-bigkey" },
            { text: "Redis 热 key 处理", link: "/qa/scenario/redis-hotkey" },
            { text: "慢查询优化案例", link: "/qa/scenario/slow-query-case" },
            { text: "索引失效案例", link: "/qa/scenario/index-case" },
            { text: "接口重放攻击防护", link: "/qa/scenario/replay-attack" },
            { text: "服务雪崩处理", link: "/qa/scenario/service-avalanche" },
            { text: "异地多活设计", link: "/qa/scenario/multi-active" },
            { text: "系统容量评估", link: "/qa/scenario/capacity-assessment" },
        ],
    },
];